version: '3.5'
services:
  portail_web_particulier:
    build: .
    env_file:
      - ./env/consumer.env
      - ./env/portail_web_particulier.env
    working_dir: /src/app
    command: "npm start"
  web_service_grand_compte:
    build: .
    env_file:
      - ./env/consumer.env
      - ./env/web_service_grand_compte.env
    working_dir: /src/app
    command: "npm start"
  agence_connect:
    build: .
    env_file:
      - ./env/consumer.env
      - ./env/agence_connect.env
    working_dir: /src/app
    command: "npm start"
  bash_virement:
    build: .
    env_file:
      - ./env/consumer.env
      - ./env/bash_virement.env
    working_dir: /src/app
    command: "npm start"
  bash_opposition:
    build: .
    env_file:
      - ./env/consumer.env
      - ./env/bash_opposition.env
    working_dir: /src/app
    command: "npm start"
